FROM ghcr.io/rails/devcontainer/images/ruby:3.3.5

RUN sudo apt-get update
RUN sudo apt-get install \
    libclang-dev \
    libinput10 \
    libfontconfig-dev \
    libxkbcommon-x11-0 \
    --no-install-recommends --yes
