name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Test in Dev Container

    steps:
    - uses: actions/checkout@v4

    - name: Create dummy SSH directory to prevent bind mount error
      run: mkdir -p ~/.ssh

    - name: Run tests in Dev Container
      uses: devcontainers/ci-action@v1
      with:
        runCmd: bundle exec rake
